src/Entity/TodoEntity.php
<?php

namespace App\Entity;

use App\Repository\TodoEntityRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TodoEntityRepository::class)]
class TodoEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $Title = null;

    #[ORM\Column(length: 250, nullable: true)]
    private ?string $Content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $DueDate = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->DueDate;
    }

    public function setDueDate(\DateTimeInterface $DueDate): self
    {
        $this->DueDate = $DueDate;

        return $this;
    }
}

src/Form/TodoFormType.php
<?php

namespace App\Form;

use App\Entity\TodoEntity;
use Doctrine\DBAL\Types\DateType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TodoFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title')
            ->add('Content')
            ->add('DueDate')
            ->add('Submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TodoEntity::class,
        ]);
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Entity\TodoEntity;
use App\Form\TodoFormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;




class TodoController extends AbstractController
{
    /** * @Route("/todos", name="todo_list") */
    
    public function todoAction(EntityManagerInterface $em)
    {
        $task = new TodoEntity();
        
        $repository = $em->getRepository(TodoEntity::class);
        /** @var TodoEntity $task */
        $task = $repository->findAll();

        if (!$task) {
            throw $this->createNotFoundException(sprintf('No tasks'));
        }

        return $this->render('tasks.html.twig', [
            'task' => $task,
        ]);

    }

    /**
     * @Route("/todos/create", name="todo_create")
     */
    public function createAction(Request $request, EntityManagerInterface $em) 
    { 
        $task = new TodoEntity(); 
        $form = $this->createForm(TodoFormType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) 
         { $em->persist($task);
             $em->flush();
            return $this->redirect($this->generateUrl( 'todo_list' )); 
         } 
         
         return $this->render('form.html.twig',['form' => $form->createView()]); 
    } 

    /**
     * @Route("/todos/update/{id}", name="todo_update")
     */
    public function updateAction($id, Request $request, EntityManagerInterface $em) 
    { 
        $repository = $em->getRepository(TodoEntity::class)->find($id);
        $task = new TodoEntity(); 
        $form = $this->createForm(TodoFormType::class, $repository); 
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) 
         { $em->persist($repository);
             $em->flush();
            return $this->redirect($this->generateUrl( 'todo_list' )); 
         } 
         
         return $this->render('update.html.twig',['form' => $form->createView()]); 
    } 
         

    /** * @Route("/todo/delete/{id}", name="todo_delete", requirements={"id" = "\d+"}, defaults={"id" = 0}) */ 
    public function deleteAction($id, EntityManagerInterface $em) 
    { 
        $repository = $em->getRepository(TodoEntity::class)->find($id); 

        if (!$repository){ 
             throw $this->createNotFoundException( 'No todo found for id '.$id ); 
            } 
        else 
        { 
            $em->remove($repository); 
            $em->flush();  
            return $this->redirect($this->generateUrl('todo_list')); 
        } 
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head> <meta charset="UTF-8" /> 
<title>My To-do Application</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
{% block body %}
{% endblock %}
{% block javascripts %}{% endblock %}
</body>
</html>

templates/form.html.twig
<!DOCTYPE html>
<html>
<head> <meta charset="UTF-8" /> 
<title>My To-do Application</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
{% form_theme form 'bootstrap_3_layout.html.twig' %}
<div class="container"> 
<hr/>
    <div class="row"> 
        <div class="col-md-6 col-md-offset-2"> 
        <h1 class="text-center">Create task</h1> 
        {{ form(form) }} 
        </div> 
    </div> 
<hr/>
</div>
</html>

templates/tasks.html.twig
<!DOCTYPE html>
<html>
<head> <meta charset="UTF-8" /> 
<title>My To-do Application</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<div class="container"> 
    <hr> 
    <div class="row"> 
        <div class="col-md-6 col-md-offset-2"> 
        <h3 class="text-center">List To-do </h3> 
        <hr/>
            {% for task in task %}
             
             <h3>{{ task.title }} </h3> 
             <p>{{ task.content }} </p>
             <a href="{{ path('todo_delete', {'id': task.id }) }}" class="btn btn-danger btn-md">Delete</a>
             <a href="{{ path('todo_update', {'id': task.id }) }}" class="btn btn-success btn-md"> Update task</a> 
             
             {% endfor %} 
             <br/>
             <br/>
             </br>
        <a href="{{ path('todo_create') }}" class="btn btn-primary btn-md"> Create task</a> 
        </div> 
        <hr/>
    </div> 
</div>
</html>

templates/update.html.twig
<!DOCTYPE html>
<html>
<head> <meta charset="UTF-8" /> 
<title>My To-do Application</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
{% form_theme form 'bootstrap_3_layout.html.twig' %}
<div class="container"> 
<hr/>
    <div class="row"> 
        <div class="col-md-6 col-md-offset-2"> 
        <h1 class="text-center">Edit Task</h1> 
        {{ form(form) }} 
        </div> 
    </div> 
<hr/>
</div>
</html>